version: "3.3"
services:
  master:
    image: fabiancrruiz/cluster-apache-spark:0.8
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0
    hostname: master
    environment:
      MASTER: spark://66.228.60.212:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 66.228.60.212
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - spark-net
    deploy:
      placement:
        constraints:
          - node.hostname==nombre-apellido

  worker-aux-fabian-ruiz:
    image: fabiancrruiz/cluster-apache-spark:0.8
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://66.228.60.212:7077
    hostname: worker-aux
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_PUBLIC_DNS: 139.144.62.82
    ports:
      - 4444:8081
    networks: 
      - spark-net
    deploy:
      placement:
        constraints:
          - node.hostname==nombre-apellido



networks:
  spark-net:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.18.0/24
